on: 
  push:
    branches:
      - main
name: 🚀 Deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 🔨 Build Project
      run: |
        npm install
        composer install
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/
        exclude: |
          vendor/**
          **/node_modules/**
